# Домашнее задание к лекции "Функции"

Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов
```
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
```
2. перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
```
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
```

Общие требования к программе:
- код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
- в коде отсутствуют глобальные переменные (за исключением **documents** и **directories**);
- пользовательский ввод обрабатывается в цикле **while** до тех пор, пока пользователь явно не завершит программу (вводом команды "**q**").

## Задание 1

### Пункт 1. Пользователь по команде "*p*" может узнать владельца документа по его номеру

Примеры работы:

1.

```
Введите команду:
p

Введите номер документа:
10006
```
Результат:  
`Владелец документа: Аристарх Павлов`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

In [8]:
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}

In [9]:
def com_p():
    number = input('Введите номер документа: ')
    res = 'Документ не найден в базе'
    for i in documents:
        if i['number'] == number:
            res = 'Владелец документа: ' + i['name']
    return res        

#com_p()

### Пункт 2. Пользователь по команде "*s*" может по номеру документа узнать на какой полке он хранится

Примеры работы:

1.

```
Введите команду:
s

Введите номер документа:
10006
```
Результат:  
`Документ хранится на полке: 2`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

In [10]:
def com_s(number):
    res = 'Документ не найден в базе'
    for i in directories.keys():
        if number in directories[i]:
            res = 'Документ хранится на полке: ' + i
    return res

#com_s('11-2')

### Пункт 3. Пользователь по команде "*l*" может увидеть полную информацию по всем документам

Пример работы:

```
Введите команду:
l
```

Результат:  
```
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [11]:
def com_l():
    res = []
    for i in range(len(documents)):
        doc = documents[i]
        res.append('№: {}, тип: {}, владелец: {}, полка хранения: {}'.format(doc['number'], 
                                                                        doc['type'], 
                                                                        doc['name'], 
                                                                        com_s(number = doc['number'])))
    return res
#print(*com_l(), sep = '\n')

### Пункт 4. Пользователь по команде "*ads*" может добавить новую полку

Примеры работы:

1.

```
Введите команду:
ads

Введите номер полки:
10
```
Результат:  
`Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.`

2.
```
Введите команду:
ads

Введите номер полки:
1
```
Результат:  
`Такая полка уже существует. Текущий перечень полок: 1, 2, 3.`

In [12]:
#функция, которая возвращает список полок, каждый номер полки в котором имеет тип int
def racks(): 
    return str([int(i) for i in [*directories]]).strip('[]')

In [21]:
def com_ads():
    number = input('Введите номер полки: ')
    if str(number) in directories.keys():
        res = f'Такая полка уже существует. Текущий перечень полок: {racks()}.'
        return res
    else:
        directories.setdefault(str(number), [])
        res = f'Полка добавлена. Текущий перечень полок: {racks()}.'
        return res

#com_ads()

### Пункт 5. Пользователь по команде "*ds*" может удалить существующую полку из данных (только если она пустая)

Примеры работы:

1.

```
Введите команду:
ds

Введите номер полки:
3
```
Результат:  
`Полка удалена. Текущий перечень полок: 1, 2.`

2.
```
Введите команду:
ds

Введите номер полки:
1
```
Результат:  
`На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
ds

Введите номер полки:
4
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

In [14]:
def com_ds():
    number = input('Введите номер полки: ')
    if number in directories.keys():
        if len(directories[number]) == 0:
            directories.pop(number)
            res = f'Полка удалена. Текущий перечень полок: {racks()}.'
        else: 
            res = f'На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: {racks()}.'
    else:
        res = f'Такой полки не существует. Текущий перечень полок: {racks()}.'
    return res
    
#com_ds()

In [250]:
def distributor(com):
    if com == 'p':     #возвращает имя владельца по номеру документа
        print(com_p())
    elif com == 's':   #возвращает номер полки по номеру документа
        number = input('Введите номер документа: ')  ##здесь требует отдельно задать ввод, так как внутри функции эта команда не предусмотрена
        print(com_s(number))
    elif com == 'l':   #выводит всю информацию по документам
        print(*com_l(), sep = '\n')              ##здесь нужен спец вывод по элементам списка
    elif com == 'ads': #добавляет пустую полку, если ее нет 
        print(com_ads())
    elif com == 'ds':  #удаляет полку, если она пустая
        print(com_ds())
    else:
        print('Команда не найдена в базе. Попробуйте еще раз.')   

In [253]:
#Итоговый код, в котором совмещаются все функции
com = input('Введите команду: ')
while com != 'q':
    distributor(com)
    com = input('Введите команду: ')

Введите команду: p
Введите номер документа: 11-2
Владелец документа: Геннадий Покемонов
Введите команду: s
Введите номер документа: 11-2
Документ хранится на полке: 1
Введите команду: l
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: Документ хранится на полке: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: Документ хранится на полке: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: Документ хранится на полке: 2
Введите команду: ads
Введите номер полки: 6
Такая полка уже существует. Текущий перечень полок: 1, 2, 3, 6.
Введите команду: ads
Введите номер полки: 8
Полка добавлена. Текущий перечень полок: 1, 2, 3, 6, 8.
Введите команду: ds
Введите номер полки: 1
На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3, 6, 8.
Введите команду: ds
Введите номер полки: 8
Полка удалена. Текущий перечень полок: 1, 2, 3, 6.
Введите команду: q


## Задание 2 (необязательное)

Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

### Пункт 1. Пользователь по команде "*ad*" может добавить новый документ в данные

Примеры работы:

1.

```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3
```
Результат:  
```
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
```

2.
```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4
```
Результат:  
```
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [20]:
def com_ad():
    doc_new = {}
    doc_new['number'] = input('Введите номер документа: ')
    doc_new['type'] = input('Введите тип документа: ')
    doc_new['name'] = input('Введите владельца документа: ')
    rack = input('Введите полку для хранения: ')
    if rack in directories.keys():
        directories[rack].append(doc_new['number'])
        documents.append(doc_new)
        print('Документ добавлен. Текущий список документов:', *com_l(), sep = '\n')
    else:
        print('Такой полки не существует. Добавьте полку командой as.\nТекущий список документов:', *com_l(), sep = '\n')

        
#com_ad()       

### Пункт 2. Пользователь по команде "*d*" может удалить документ из данных

Примеры работы:

1.

```
Введите команду:
d

Введите номер документа:
10006
```
Результат:  
```
Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
```

2.
```
Введите команду:
d

Введите номер документа:
123456
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [19]:
def com_d():
    number = input('Введите номер документа: ')
    list_numbers = {documents[i]['number']: i for i in range(len(documents))}
    if number in list_numbers:
        documents.pop(list_numbers[number])
        rack = com_s(number).split()[-1]
        directories[rack].remove(number)
        print('Документ удален.\nТекущий список документов:', *com_l(), sep = '\n')
    else:
        print('Документ не найден в базе.\nТекущий список документов:', *com_l(), sep = '\n')

#com_d()

### Пункт 3. Пользователь по команде "*m*" может переместить документ с полки на полку

Примеры работы:

1.

```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
```
Результат:  
```
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

2.
```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [22]:
def com_m():
    number = input('Введите номер документа: ')
    rack_new = input('Введите номер полки: ')
    if number in [el['number'] for el in documents]:
        if rack_new in directories.keys():
            rack_old = com_s(number).split()[-1]
            directories[rack_old].remove(number)
            directories[rack_new].append(number)
            print('Документ перемещен.\nТекущий список документов:', *com_l(), sep = '\n')
        else:
            print(f'Такой полки не существует. Текущий перечень полок: {racks()}.')
    else:
        print('Документ не найден в базе.\nТекущий список документов:', *com_l(), sep = '\n')

#com_m()

In [258]:
def distributor_all(com):
    if com == 'p':      #возвращает имя владельца по номеру документа
        print(com_p())
    elif com == 's':    #возвращает номер полки по номеру документа
        number = input('Введите номер документа: ')     #здесь требует отдельно задать ввод, так как внутри функции эта команда не предусмотрена
        print(com_s(number))
    elif com == 'l':    #выводит всю информацию по документам
        print(*com_l(), sep = '\n')                 #здесь нужен спец вывод по элементам списка
    elif com == 'ads':  #добавляет пустую полку, если ее нет 
        print(com_ads())
    elif com == 'ds':   #удаляет полку, если она пустая
        print(com_ds())
    elif com == 'ad':   #добавляет документ в данные, если указана существующая полка
        com_ad()        ##ничего не возвращает, просто печатает текущий перечень файлов с выполненным действием (добавление дока или нет)
    elif com == 'd':    #удаляет документ из данных
        com_d()         #ничего не возвращает, просто печатает текущий перечень файлов с выполненным действием (удалением или нет)
    elif com == 'm':    #перемещает док с одной полки на другую
        com_m()         #ничего не возвращает, просто печатает текущий перечень файлов с выполненным действием (перемещением дока или нет)
    else:
        print('Команда не найдена в базе. Попробуйте еще раз.')   

In [259]:
#Итоговый код, в котором совмещаются основые и дополнительные функции
com = input('Введите команду: ')
while com != 'q':
    distributor_all(com)
    com = input('Введите команду: ')

Введите команду: ad
Введите номер документа: 54123
Введите тип документа: password
Введите владельца документа: MaxiXu
Введите полку для хранения: 6
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: Документ хранится на полке: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: Документ хранится на полке: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: Документ хранится на полке: 2
№: 54123, тип: password, владелец: MaxiXu, полка хранения: Документ хранится на полке: 6
Введите команду: ad
Введите номер документа: 1111
Введите тип документа: multipassport
Введите владельца документа: Lilu
Введите полку для хранения: 8
Такой полки не существует. Добавьте полку командой as.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: Документ хранится на полке: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: Документ х

#### ПРИМЕЧАНИЕ
Домашнее задание сдается ссылкой на репозиторий [GitHub](https://github.com/).
Не сможем проверить или помочь, если вы пришлете:
- файлы;
- архивы;
- скриншоты кода.

Все обсуждения и консультации по выполнению домашнего задания ведутся только на соответствующем канале в slack.

##### Как правильно задавать вопросы аспирантам, преподавателям и коллегам
Прежде чем задать вопрос, попробуйте найти ответ в интернете. Навык самостоятельного поиска информации — один из важнейших. Каждый практикующий специалист любого уровня делает это ежедневно.

Сформулируйте вопрос по алгоритму:  
1) Что я делаю?  
2) Какого результата я ожидаю?  
3) Как фактический результат отличается от ожидаемого?  
4) Что я уже попробовал сделать, чтобы исправить проблему?  

По возможности прикрепите к вопросу скриншоты либо ссылки на код. Не выкладывайте все решение, оставляйте только проблемный и воспроизводимый участок кода.